### ISSUE TITLE
using compose starts fail

### ISSUE THREAD

**Issue by wangweitung** [KodCloud-dev/docker#22]
way: docker compose 

```
git clone https://github.com/KodCloud-dev/docker.git kodbox
cd ./kodbox/compose/
```
db.env中设置数据库密码
```
MYSQL_PASSWORD=123456
MYSQL_DATABASE=kodbox
MYSQL_USER=kodbox
```
docker-compose.yml
```
version: '3.5'

services:
  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - "./db:/var/lib/mysql"       #./db是数据库持久化目录，可以修改
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    env_file:
      - db.env
      
  app:
    image: kodcloud/kodbox:latest
    #image: kodcloud/kodbox:1.49.01
    restart: always
    ports:
      - 2380:80                       #左边80是使用端口，可以修改
    volumes:
      - "./site:/var/www/html"      #./site是站点目录位置，可以修改
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    restart: always

```

docker-compose up -d

error log:
```
{
    "code": "10001",
    "timeUse": "0.0075",
    "timeNow": "1703320111.9544",
    "data": "登录已失效，请重新登录!"
}
```
